version: '3'
services:
  
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest" 
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Your_password123"
    # volumes:
    #     - container-volume:/var/opt/mssql/database
    ports:
        - 1433:1433 

volumes:
  container-volume: 